<?php
    $url = $_SERVER['REQUEST_URI'];
    $redirecionar = '';
    //Usar para redirecionamento na mesma página
    if($url === '/'){
        $redirecionar = '#';
    }else{
        $redirecionar = '/#';
    }
    session_start();
    if (!isset($_SESSION['usuario'])) {
        $_SESSION['usuario'] = 'cliente';
    }
    if (!isset($_SESSION['logado'])) {
        $_SESSION['logado'] = false;
    }
    if($_SESSION['usuario'] != 'cliente' ||  !$_SESSION['logado'] != false){
        $_SESSION['usuario'] = $_SESSION['usuario'];
        $_SESSION['logado'] = $_SESSION['logado'];
    }
?>
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pizzaria - Delicias da Mamma</title>
    <!--Icon-->
    <link rel="icon" href="Midias/Imgs/logo-semfundo.png">
    <!--Font Awesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!--Bootstrap CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <!--Bootstrap JS-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!--JQuery-->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <!--CSS-->
    <link rel="stylesheet" href="Midias/Style/Style.css">
    <!--JS-->
    <script src="/Midias/Js/js.js"></script>
</head>
<body>
    <header class="off-print">
        <section class="logo">
            <a <?php if($_SESSION['usuario'] == 'cliente'){ ?>href="/" <?php }else{ ?> href="#" <?php }?>><img src="Midias/Imgs/logo-semfundo.png" alt="Logo delícias da mamma"></a>
        </section>
        <section class="mobileNavDisplay">
            <button class="btn-mobile" id="mobileNavBtn"><i class="fa-solid fa-bars"></i></button>
        </section>
        <nav class="desktopNav" id="desktopNav">
            <ul>
            <?php
                if($_SESSION['usuario'] == 'cliente'){ 
            ?>
                <a href="/">
                    <li>Início</li>
                </a>
                <a href="/cardapio">
                    <li>Cardápio</li>
                </a>
                <a href="/delivery">
                    <li>Delivery</li>
                </a>
                <a href="/avaliacao">
                    <li>Avaliação</li>
                </a>
                <?php
                if($_SESSION['logado'] == false){ 
                ?>
                <a href="/login">
                    <li>Login</li>
                </a>
                <?php } ?>
            <?php } ?>
            <?php
                if($_SESSION['usuario'] == 'funcionario' || $_SESSION['usuario'] == 'adm' || $_SESSION['usuario'] == 'caixa'  || $_SESSION['logado'] == true){ 
            ?>
                <a href="/deslogar">
                    <li>Deslogar <i class="fa-solid fa-right-from-bracket deslogar"></i></li>
                </a>
            <?php } ?>
            </ul>
        </nav>
    </header>
        <nav class="mobileNav" id="mobileNav">
            <ul>
            <?php
                if($_SESSION['usuario'] == 'cliente'){ 
            ?>
                <a href="/">
                    <li>Início</li>
                </a>
                <a href="/cardapio">
                    <li>Cardápio</li>
                </a>
                <a href="/delivery">
                    <li>Delivery</li>
                </a>
                <a href="/avaliacao">
                    <li>Avaliação</li>
                </a>
                <?php
                if($_SESSION['logado'] == false){ 
                ?>
                <a href="/login">
                    <li>Login</li>
                </a>
                <?php } ?>
                <a class="off-mobile" href="#sobrenos">
                    <li>image</li>
                </a>
                
            <?php } ?>
            <?php
                if($_SESSION['usuario'] == 'funcionario' || $_SESSION['usuario'] == 'adm' || $_SESSION['usuario'] == 'caixa'  || $_SESSION['logado'] == true){ 
            ?>
                <a href="/deslogar">
                    <li>Deslogar <i class="fa-solid fa-right-from-bracket deslogar"></i></li>
                </a>
            <?php } ?>
            </ul>
        </nav>
